// @generated by protobuf-ts 2.9.0 with parameter long_type_bigint,server_generic
// @generated from protobuf file "services/network.proto" (package "ubt.services", syntax proto3)
// tslint:disable
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { ListNetworksRequest } from "./network";
import { Network } from "../models";
import { NetworkId } from "../models";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ubt.services.UbtNetworkService
 */
export interface IUbtNetworkService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: getNetwork(ubt.NetworkId) returns (ubt.Network);
     */
    getNetwork(request: NetworkId, context: T): Promise<Network>;
    /**
     * rpc getNetworkStatus(NetworkId) returns (NetworkStatus);
     *
     * @generated from protobuf rpc: listNetworks(ubt.services.ListNetworksRequest) returns (stream ubt.Network);
     */
    listNetworks(request: ListNetworksRequest, responses: RpcInputStream<Network>, context: T): Promise<void>;
}
