VERSION 0.7

buf:
  FROM bufbuild/buf:1.26.1
  SAVE ARTIFACT /usr/local/bin/buf AS LOCAL ./buf

generate:
  FROM node:18-alpine
  COPY . /build/
  COPY +buf/buf /usr/local/bin/buf
  BUILD ./proto+files
  COPY  ./proto+files/proto /build/proto
  RUN cd /build && npm install && npm run generate
  SAVE ARTIFACT /build/src/api/proto AS LOCAL ./src/api/proto

build:
  FROM node:18-alpine
  COPY . /build/
  WORKDIR /build
  RUN npm install
  RUN npm run build
  RUN npm run test

publish:
  ARG EARTHLY_PUSH
  ARG version
  FROM node:18-alpine
  COPY . /build/
  WORKDIR /build
  RUN npm install
  RUN export VERSION=${version}; npm run prepare-publish && echo $VERSION
  IF [ "$EARTHLY_PUSH" = "true" ]
    RUN npm run clean-publish
  ELSE
    RUN cd dist && npm pack
  END