// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/ext/trx.proto

package ext

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trx_GetTransactionInfo_FullMethodName = "/ubt.services.ext.Trx/getTransactionInfo"
)

// TrxClient is the client API for Trx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrxClient interface {
	// return extended transaction info for tron, contains full fee amount while standard Transaction contains only energy part
	GetTransactionInfo(ctx context.Context, in *TransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfoResponse, error)
}

type trxClient struct {
	cc grpc.ClientConnInterface
}

func NewTrxClient(cc grpc.ClientConnInterface) TrxClient {
	return &trxClient{cc}
}

func (c *trxClient) GetTransactionInfo(ctx context.Context, in *TransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionInfoResponse)
	err := c.cc.Invoke(ctx, Trx_GetTransactionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrxServer is the server API for Trx service.
// All implementations must embed UnimplementedTrxServer
// for forward compatibility.
type TrxServer interface {
	// return extended transaction info for tron, contains full fee amount while standard Transaction contains only energy part
	GetTransactionInfo(context.Context, *TransactionInfoRequest) (*TransactionInfoResponse, error)
	mustEmbedUnimplementedTrxServer()
}

// UnimplementedTrxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrxServer struct{}

func (UnimplementedTrxServer) GetTransactionInfo(context.Context, *TransactionInfoRequest) (*TransactionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionInfo not implemented")
}
func (UnimplementedTrxServer) mustEmbedUnimplementedTrxServer() {}
func (UnimplementedTrxServer) testEmbeddedByValue()             {}

// UnsafeTrxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrxServer will
// result in compilation errors.
type UnsafeTrxServer interface {
	mustEmbedUnimplementedTrxServer()
}

func RegisterTrxServer(s grpc.ServiceRegistrar, srv TrxServer) {
	// If the following call pancis, it indicates UnimplementedTrxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trx_ServiceDesc, srv)
}

func _Trx_GetTransactionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrxServer).GetTransactionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trx_GetTransactionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrxServer).GetTransactionInfo(ctx, req.(*TransactionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trx_ServiceDesc is the grpc.ServiceDesc for Trx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ubt.services.ext.Trx",
	HandlerType: (*TrxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTransactionInfo",
			Handler:    _Trx_GetTransactionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/ext/trx.proto",
}
