// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/network.proto

package services

import (
	context "context"
	proto "github.com/ubtr/ubt/go/api/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UbtChainService_GetChain_FullMethodName   = "/ubt.services.UbtChainService/getChain"
	UbtChainService_ListChains_FullMethodName = "/ubt.services.UbtChainService/listChains"
)

// UbtChainServiceClient is the client API for UbtChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UbtChainServiceClient interface {
	GetChain(ctx context.Context, in *proto.ChainId, opts ...grpc.CallOption) (*proto.Chain, error)
	// rpc getChainStatus(ChainId) returns (ChainStatus);
	ListChains(ctx context.Context, in *ListChainsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.Chain], error)
}

type ubtChainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUbtChainServiceClient(cc grpc.ClientConnInterface) UbtChainServiceClient {
	return &ubtChainServiceClient{cc}
}

func (c *ubtChainServiceClient) GetChain(ctx context.Context, in *proto.ChainId, opts ...grpc.CallOption) (*proto.Chain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(proto.Chain)
	err := c.cc.Invoke(ctx, UbtChainService_GetChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ubtChainServiceClient) ListChains(ctx context.Context, in *ListChainsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.Chain], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UbtChainService_ServiceDesc.Streams[0], UbtChainService_ListChains_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListChainsRequest, proto.Chain]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UbtChainService_ListChainsClient = grpc.ServerStreamingClient[proto.Chain]

// UbtChainServiceServer is the server API for UbtChainService service.
// All implementations must embed UnimplementedUbtChainServiceServer
// for forward compatibility.
type UbtChainServiceServer interface {
	GetChain(context.Context, *proto.ChainId) (*proto.Chain, error)
	// rpc getChainStatus(ChainId) returns (ChainStatus);
	ListChains(*ListChainsRequest, grpc.ServerStreamingServer[proto.Chain]) error
	mustEmbedUnimplementedUbtChainServiceServer()
}

// UnimplementedUbtChainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUbtChainServiceServer struct{}

func (UnimplementedUbtChainServiceServer) GetChain(context.Context, *proto.ChainId) (*proto.Chain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChain not implemented")
}
func (UnimplementedUbtChainServiceServer) ListChains(*ListChainsRequest, grpc.ServerStreamingServer[proto.Chain]) error {
	return status.Errorf(codes.Unimplemented, "method ListChains not implemented")
}
func (UnimplementedUbtChainServiceServer) mustEmbedUnimplementedUbtChainServiceServer() {}
func (UnimplementedUbtChainServiceServer) testEmbeddedByValue()                         {}

// UnsafeUbtChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UbtChainServiceServer will
// result in compilation errors.
type UnsafeUbtChainServiceServer interface {
	mustEmbedUnimplementedUbtChainServiceServer()
}

func RegisterUbtChainServiceServer(s grpc.ServiceRegistrar, srv UbtChainServiceServer) {
	// If the following call pancis, it indicates UnimplementedUbtChainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UbtChainService_ServiceDesc, srv)
}

func _UbtChainService_GetChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.ChainId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UbtChainServiceServer).GetChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UbtChainService_GetChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UbtChainServiceServer).GetChain(ctx, req.(*proto.ChainId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UbtChainService_ListChains_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListChainsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UbtChainServiceServer).ListChains(m, &grpc.GenericServerStream[ListChainsRequest, proto.Chain]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UbtChainService_ListChainsServer = grpc.ServerStreamingServer[proto.Chain]

// UbtChainService_ServiceDesc is the grpc.ServiceDesc for UbtChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UbtChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ubt.services.UbtChainService",
	HandlerType: (*UbtChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChain",
			Handler:    _UbtChainService_GetChain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "listChains",
			Handler:       _UbtChainService_ListChains_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/network.proto",
}
