VERSION 0.7

generate:
  FROM bufbuild/buf:1.26.1
  BUILD ./proto+files
  COPY  ./proto+files/proto /build/proto
  COPY ./buf.gen.yaml /build/buf.gen.yaml
  COPY ./buf.work.yaml /build/buf.work.yaml
  RUN cd /build && buf generate
  SAVE ARTIFACT /build/api/proto AS LOCAL ./api/proto


build:
  FROM bufbuild/buf:1.26.1
  BUILD ./proto+files
  COPY  ./proto+files/proto /build/proto
  COPY ./buf.gen.yaml /build/buf.gen.yaml
  COPY ./buf.work.yaml /build/buf.work.yaml
  RUN cd /build && buf generate
  SAVE ARTIFACT /build/api/proto AS LOCAL ./api/proto